org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

# အောက်ပါ line နှစ်ကြောင်းကို အသစ်ထည့်ပါ (အရေးကြီးဆုံး)
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false