// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDne0xkhE5MR7USGngcdJR8OofwABXPk7A',
    appId: '1:158882196078:web:0e32f3922c2fc3d040d47f',
    messagingSenderId: '158882196078',
    projectId: 'fir-bloglessonrubylearner',
    authDomain: 'fir-bloglessonrubylearner.firebaseapp.com',
    storageBucket: 'fir-bloglessonrubylearner.firebasestorage.app',
    measurementId: 'G-74YPPE6YM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPm6Hf9BV3LDyHTj_xKvFenGUwszV1ydo',
    appId: '1:158882196078:android:231be413801fa15a40d47f',
    messagingSenderId: '158882196078',
    projectId: 'fir-bloglessonrubylearner',
    storageBucket: 'fir-bloglessonrubylearner.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL0cbW242eAMylQxolNqt8hNh-OcAWJSM',
    appId: '1:158882196078:ios:b9f197f650c7765640d47f',
    messagingSenderId: '158882196078',
    projectId: 'fir-bloglessonrubylearner',
    storageBucket: 'fir-bloglessonrubylearner.firebasestorage.app',
    iosBundleId: 'com.tpm.firebaseBlogAppLesson',
  );
}
